version: '2'
services:
    htf-app:
        image: htf
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://htf-postgresql:5432/HTF
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    htf-postgresql:
        extends:
            file: postgresql.yml
            service: htf-postgresql
