version: '2'
services:
    htf-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/HTF/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=HTF
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
